on:
  push:
    branches:
  pull_request:
    branches:
      -'*'
      -'!ga-ignore-*'
env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-COT-2-1-chocolatine-jordan.amouzoun.git"
  EXECUTABLES: "107tranfer"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
      - run: check.sh $(pwd) $(pwd)
      - run: echo "::error::$(cat coding-style-reports.log)"