name: GitHub Actions Demo
run-name: ${{ github.actor }} mirror
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2028/B-DOP-200-COT-2-1-bschocolatine-jordan.amouzoun.git
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}