name: GitHub Actions Demo
run-name: ${{ github.actor }} get the repo size
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: .
    - run: echo ${{ github.brach.base.ref }}
    - run: du -skh --exclude=".git"